# Generated by Django 3.1.4 on 2021-06-13 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('Bank Transfer Offline', 'Bank Transfer Offline'), ('Khalti', 'Khalti'), ('Esewa', 'Esewa')], max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Payment Pending', 'Payment Pending'), ('Verified', 'Verified'), ('Payment Failed', 'Payment Failed'), ('Completed', 'Completed'), ('To be verified', 'To be verified')], default='Payment Pending', max_length=100)),
                ('done_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('paid_for', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='course.course')),
            ],
        ),
    ]
